In [1]:
import numpy as np

In [2]:
input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
AND_out = np.array([0, 0, 0, 1])
AND_out

array([0, 0, 0, 1])

In [4]:
OR_out = np.array([0, 1, 1, 1])
OR_out

array([0, 1, 1, 1])

In [5]:
AND_Function = np.array([1 if np.sum(i) > 1.5 else 0 for i in input])
AND_Function

array([0, 0, 0, 1])

In [6]:
np.allclose(AND_out, AND_Function)

True

In [7]:
OR_Function = np.array([1 if np.sum(i) > 0.5 else 0 for i in input])
OR_Function

array([0, 1, 1, 1])

In [8]:
np.allclose(OR_out, OR_Function)

True